name: Automation CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'   # Daily at 3 AM UTC (8:30 AM IST)

jobs:

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run API Tests
        run: mvn clean test -Dcucumber.filter.tags="@api"

      - name: Upload API Reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: target/


  ui-tests:
    name: UI Tests (Selenium Grid)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Start Selenium Grid
        run: docker compose up -d

      - name: Wait for Selenium Grid to be ready
        run: |
          echo "Waiting for Selenium Grid..."
          for i in {1..30}; do
            if curl -s http://localhost:4444/status | grep '"ready": true'; then
              echo "Selenium Grid is ready!"
              break
            fi
            echo "Grid not ready yet... retrying"
            sleep 2
          done

      #  FIRST RUN
      - name: Run UI Tests (First Run)
        run: mvn clean test -Dcucumber.filter.tags="@ui" -Dexecution=grid || true

      # RERUN FAILED SCENARIOS
      - name: Re-run Failed Scenarios
        run: |
          if [ -s target/failed.txt ]; then
            echo "Re-running failed scenarios..."
            mvn test -Dexecution=grid -Dtest=runner.FailedTestRunner
          else
            echo "No failed scenarios to rerun."
          fi

      - name: Stop Selenium Grid
        run: docker compose down

      - name: Upload UI Reports
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: target/